export const MENU = [
    "Mixed Veg",
    "Chatpate Chole",
    "Tandoori Aloo",
    "Mushroom Salsa",
    "Mushroom Tikka",
    "Veggie Delight",
    "Masala Paneer Tikka",
    "Fiery Panner Tikka",
    "Paneer Mushroom",
    "Veg Feast",
    "Egg Chatpata",
    "Egg Potato",
    "Chicken Seekh",
    "Fiery Seekh Kebab",
    "Chicken Delight",
    "Sizzling Chicken",
    "Reshmi Kebab",
    "Chicken Bhuna",
    "Masala Chicken Tikka",
    "Chicken Mushroom",
    "Smoked Chicken and Corn",
    "Mutton Boti",
    "Chicken Feast",
    "Jumbo Chicken Wrap",
    "Vegetarian Lasagne",
    "Chicken Rice Feast",
    "Grilled Chicken Breast"
]